name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (if any)
        run: |
          if [ -f Podfile ]; then
            pod install
          fi

      - name: Build
        run: |
          xcodebuild clean test \
            -project "CleanArchitectureDemo.xcodeproj" \
            -scheme "CleanArchitectureDemo" \
            -destination 'platform=iOS Simulator,name=iPhone 15'
