name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build App
        run: |
          xcodebuild clean build \
          -scheme CleanArchitectureDemo \
          -destination 'platform=iOS Simulator,name=iPhone 15'

